server:
  port: 9090
spring:
  datasource:
    username: sa
    password: null
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: praveencloud06@gmail.com
    password: abcd
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

app: 
  messages: 
      pwdRecoverSucc: Password Sent To Your Email
      pwdRecoverFail: Invalid Email Id
      accRegSucc: Registration Almost Done, Check Your Mail To Unlock Account
      accRegFail: Account Creation Failed
      userAlreadyRegistered: User Already Registered
      accLocked: Account is locked
      invalidCredentials: Credentials are invalid
  